#!/bin/sh
echo "######################################################"
echo "###################  REMINDER ########################"
echo "######################################################"
echo ""
echo "~/.bashrc and ~/.bash_profile have not been touched."
echo "To automatically start the VM add"
echo ""
echo "  source \$HOME/.shell/.start_pywm.sh"
echo ""
echo "to your ~/.bashrc or ~/.bash_profile"
echo ""
echo "######################################################"
echo "######################################################"
