#!/bin/sh
echo "######################################################"
echo "###################  REMINDER ########################"
echo "######################################################"
echo ""
echo "~/.zshrc has not been touched."
echo "To use the configuration add"
echo ""
echo "  source \$HOME/.shell/gsync.sh"
echo ""
echo "to your ~/.zshrc"
echo ""
echo "######################################################"
echo "######################################################"
