#!/bin/sh
echo "######################################################"
echo "###################  REMINDER ########################"
echo "######################################################"
echo ""
echo "~/.bashrc and ~/.bash_profile have not been touched."
echo "To use the configuration add"
echo ""
echo "  source \$HOME/.shell/.bashrc"
echo ""
echo "to your ~/.bashrc or ~/.bash_profile"
echo ""
echo "######################################################"
echo "######################################################"
